In [1]:
# %load ../standard_import.txt
import pandas as pd ##Or use SFrame
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.preprocessing import scale #用来对数据预处理，包括无量纲化，特征二值化，定性数据量化等
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from scipy.cluster import hierarchy

%matplotlib inline
plt.style.use('seaborn-white')

## Clustering
### K-means Clustering

In [6]:
#Generate data
np.random.seed(2)
X=np.random.standard_normal((50,2))
X[:25,0]=X[:25,0]+3
X[:25,1]=X[:25,1]-4

#### k=2

In [7]:
km1=KMeans(n_clusters=2, n_init=20)
km1.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=20, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [8]:
km1.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1], dtype=int32)

#### k=3

In [9]:
np.random.seed(4)
km2=KMeans(n_clusters=3,n_init=20)
km2.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=20, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [10]:
pd.Series(km2.labels_).value_counts()

1    21
0    20
2     9
dtype: int64

In [11]:
km2.cluster_centers_

array([[-0.27876523,  0.51224152],
       [ 2.82805911, -4.11351797],
       [ 0.69945422, -2.14934345]])

In [12]:
km2.labels_

array([1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1,
       1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 2], dtype=int32)

In [13]:
km2.inertia_

68.973792009397258

In [ ]:
fig, (ax1, ax2)=plt.subplots(1,2, figsize=(14,5))

